# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - 'size' refers to the length of the shared border between solid black and solid white rectangle.
#   See README.md or https://github.com/AprilRobotics/apriltag/wiki/AprilTag-User-Guide#pose-estimation for details.
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     ...
#   ]
# standalone_tags:
#   [
    # {id: 0, size: 0.13374},
    # {id: 1, size: 0.04634},
    # {id: 2, size: 0.04634},
    # {id: 3, size: 0.04634},
    # {id: 4, size: 0.04634},
    # {id: 5, size: 0.04634},
    # {id: 6, size: 0.04634},
    # {id: 7, size: 0.04634},
    # {id: 8, size: 0.04634},
    # {id: 9, size: 0.04634},
  # ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]
tag_bundles:
  [
    {
      name: 'my_bundle',
      layout:
        [
          {id: 5, size: 0.04634, x: 0, y: 0,},
          {id: 3, size: 0.04634, x: 0.0572, y: 0.0572,},
          {id: 4, size: 0.04634, x: -0.0572, y: 0,},          
          {id: 2, size: 0.04634, x: 0, y: 0.0572,},
          {id: 1, size: 0.04634, x: -0.0572, y: 0.0572,},
          {id: 7, size: 0.04634, x: -0.0572, y: -0.0572,},          
          {id: 9, size: 0.04634, x: 0.0572, y: -0.0572,},
          {id: 8, size: 0.04634, x: 0, y: -0.0572,},
          {id: 6, size: 0.04634, x: 0.0572, y: 0,},
        ]
    },
  ]
  # tag_bundles:
  #   [
  #     {
  #       name: 'my_bundle',
  #       layout:
  #         [
  #           {id: 5, size: 0.05, x: 0.0000, y: 0.0000, z: 0.0000, qw: 1.0000, qx: 0.0000, qy: 0.0000, qz: 0.0000},
  #           {id: 3, size: 0.05, x: 0.0555, y: 0.0557, z: -0.0018, qw: 0.9999, qx: -0.0053, qy: 0.0148, qz: 0.0001},
  #           {id: 4, size: 0.05, x: -0.0554, y: 0.0002, z: -0.0000, qw: 0.9999, qx: 0.0029, qy: -0.0161, qz: -0.0005},
  #           {id: 2, size: 0.05, x: 0.0000, y: 0.0559, z: 0.0000, qw: 1.0000, qx: 0.0077, qy: 0.0063, qz: -0.0005},
  #           {id: 1, size: 0.05, x: -0.0554, y: 0.0559, z: 0.0004, qw: 0.9998, qx: 0.0138, qy: -0.0116, qz: -0.0008},
  #           {id: 7, size: 0.05, x: -0.0555, y: -0.0556, z: -0.0006, qw: 0.9999, qx: 0.0021, qy: -0.0139, qz: -0.0001},
  #           {id: 9, size: 0.05, x: 0.0555, y: -0.0561, z: -0.0021, qw: 0.9999, qx: -0.0030, qy: 0.0114, qz: -0.0001},
  #           {id: 8, size: 0.05, x: -0.0001, y: -0.0558, z: -0.0005, qw: 1.0000, qx: 0.0065, qy: -0.0007, qz: -0.0004},
  #           {id: 6, size: 0.05, x: 0.0555, y: -0.0001, z: -0.0018, qw: 0.9999, qx: -0.0016, qy: 0.0161, qz: -0.0001}
  #         ]
  #     }
  #   ]
